### ISSUE TITLE
Question: How to deal with "long" posts

### ISSUE THREAD

**Issue by TheAlexLichter** [algolia/algoliasearch-laravel-example#1]
Hey!

I want to integrate Algolia into an upcoming project. Unfortunately, most Models have a large content (sometimes > 5000 characters). Is there a way to deal with these long content models properly (other than just limiting the string to 5000 characters before submitting the data to Algolia) and to comply with [the docs](https://www.algolia.com/doc/guides/indexing/structuring-your-data/?language=laravel#indexing-long-documents)?

**Comment by nunomaduro** [comment]
You can use `Scout Extended` for that: https://www.algolia.com/doc/framework-integration/laravel/advanced-use-cases/split-large-records.
